### ISSUE TITLE
does not work for modules required as dependencies

### ISSUE THREAD

**Issue by cflynn07** [Runnable/loadenv#2]
loadenv appears to only load .env files from the parent module's config folder if run as part of a module that is a dependency of a parent

app-root-path appears to only return the parent path
https://github.com/Runnable/loadenv/blob/master/index.js#L23

ex:
/workspace/app/config/
/workspace/app/node_modules/some-module/ <-- loads config from app/config

**Comment by bkendall** [comment]
thought: does it occur if the parent module does _not_ include `loadenv` (or `app-root-path` for that matter)? could it be `require` caching it that causes this behavior?

**Comment by cflynn07** [comment]
checked with logs to verify, doesn't appear to be due to require caching. app-root-path may not be necessary, `dirname+../../../` works for identifying the root directory of the module since loadenv is located in node_modules
